// Import necessary modules
import type { Metadata } from "next";
import { Inter, Dancing_Script, Nunito } from "@next/font/google";

// Import global CSS file
import "./globals.css";

// Import components
import Navbar from '../components/Navbar/Navbar';
import Footer from "../components/Footer/Footer";

// Define fonts with their respective configurations
const inter = Inter({ subsets: ["latin"], weight: ['400'], variable: '--font-inter' });
const dance = Dancing_Script({ subsets: ["latin"], weight: ['400'], variable: '--font-dance' });
const nunito = Nunito({ subsets: ["latin"], weight: ['900'], variable: '--font-nunito' });

// Define metadata
export const metadata: Metadata = {
  title: "PlotPlanet",
  description: "Generated by create next app",
};

// Define RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${dance.variable}  ${nunito.variable}`}> {/* Use template literals to concatenate class names */}
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html >
  );
}
